-- This analysis file serves as a report to demonstrate how the final mart tables can be used
-- to answer key business questions for different teams.

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ANALYSIS 1: mart_customer_journey (The Core Request)
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- AREA OF INTEREST: All teams (Data, Product, Marketing, Customer Success)
-- DESCRIPTION: The `mart_customer_journey` table is the foundational, event-level fact table.
-- It provides a complete, chronological "movie" of every customer interaction, from purchase
-- to onboarding and ongoing usage. It includes calculated metrics like purchase number and
-- running total spend, which are essential for understanding the customer lifecycle.

select
    event_timestamp,
    customer_id,
    product_name,
    event_category,
    event_type,
    purchase_number,
    running_total_spend
from {{ ref('mart_customer_journey') }}
where customer_id = 'cust_101'
order by event_timestamp

-- LOOKER STUDIO VISUALIZATION: A Table chart, filtered for a specific customer, to trace their entire journey.

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ANALYSIS 2: Time to First Use
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- AREA OF INTEREST: Product Management, Customer Success
-- DESCRIPTION: Calculates the average time in days from purchase to the first usage event for each product.
-- This helps identify products with potential onboarding friction.

select
    p.product_name,
    avg(s.time_to_first_use_days) as avg_days_to_first_use
from {{ ref('fct_customer_product_summary') }} as s
join {{ ref('base_products') }} as p on s.product_id = p.product_id
group by 1
order by 2

-- LOOKER STUDIO VISUALIZATION: A Bar Chart comparing the average adoption time across different products.

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ANALYSIS 3: First Purchase Analysis
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- AREA OF INTEREST: Product Management, Product Marketing
-- DESCRIPTION: Identifies which products are most commonly purchased first by new customers.
-- This is key for understanding which products are the main entry points into the ecosystem.

select
    product_name,
    count(distinct customer_id) as total_first_purchases
from {{ ref('mart_customer_journey') }}
where purchase_number = 1
group by 1
order by 2 desc

-- LOOKER STUDIO VISUALIZATION: A Pie Chart or Bar Chart showing the distribution of first purchases.

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ANALYSIS 4: Onboarding Funnel
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- AREA OF INTEREST: Customer Success, Product Management
-- DESCRIPTION: Shows the conversion rate through the key onboarding steps: Registered -> Downloaded -> Installed.
-- This helps pinpoint where users might be dropping off during the setup process.

with event_counts as (
    select
        event_type,
        count(distinct customer_id) as customer_count
    from {{ ref('mart_customer_journey') }}
    where event_category in ('registered', 'downloaded', 'installed')
    group by 1
)
select * from event_counts

-- LOOKER STUDIO VISUALIZATION: A Funnel Chart to visualize the drop-off at each onboarding step.

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ANALYSIS 5: Customer Lifetime Value (CLV)
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- AREA OF INTEREST: Product Marketing, Finance
-- DESCRIPTION: Identifies the most valuable customers based on their total spending.
-- This is crucial for segmentation and focusing marketing efforts.

select
    customer_name,
    customer_lifetime_value
from {{ ref('dim_customers_enriched') }}
order by customer_lifetime_value desc

-- LOOKER STUDIO VISUALIZATION: A Table or Bar Chart showing the top customers by their lifetime value.

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ANALYSIS 6: Monthly Revenue Trend by Product
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- AREA OF INTEREST: Finance, Product Marketing
-- DESCRIPTION: Shows the total revenue generated by each product on a monthly basis.
-- This is essential for tracking performance and identifying sales trends. This query
-- demonstrates the utility of the pre-aggregated monthly summary table.

select
    summary_month,
    product_name,
    monthly_purchase_amount
from {{ ref('agg_customer_monthly_summary') }}
order by summary_month, product_name

-- LOOKER STUDIO VISUALIZATION: A Stacked Bar Chart with the month on the x-axis and revenue on the y-axis, stacked by product_name.